#!/bin/bash
iptables com regras de firewall
############ EXTRA STUFF TO HELP HIGH TRAFFIC (DDOS) ##################

###################################################################################################################
# _|___|___|___|___|___|___|___|___|___|___|___|___|                                                             ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__        IPTables: Linux's Main line of Defense               ##
# _|___|___|___|___|___|___|___|___|___|___|___|___|        IPTables: Linux's way of saying no to DoS kids       ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__                                                             ##    
# _|___|___|___|___|___|___|___|___|___|___|___|___|        Version 1.0.0 -                                      ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__        IPTables Script created by p0w3r0ff                  ##
# _|___|___|___|___|___|___|___|___|___|___|___|___|                                                             ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__        Sources used and Studied;                            ##
# _|___|___|___|___|___|___|___|___|___|___|___|___|                                                             ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__     http://ipset.netfilter.org/iptables.man.html            ##
# _|___|___|___|___|___|___|___|___|___|___|___|___|                                                             ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__                                                             ##
###################################################################################################################

# Instalar e configurar Fail2Ban
apt-get update
apt-get install -y fail2ban

# Configurar jail.local para SSH e Apache
cat <<EOL > /etc/fail2ban/jail.local
[sshd]
enabled = true

[apache]
enabled = true
EOL

# Reiniciar Fail2Ban
service fail2ban restart

# Instalar e configurar ModSecurity
apt-get install -y libapache2-modsecurity
cp /etc/modsecurity/modsecurity.conf-recommended /etc/modsecurity/modsecurity.conf

# Configurar SecRuleEngine
sed -i 's/SecRuleEngine DetectionOnly/SecRuleEngine On/' /etc/modsecurity/modsecurity.conf

# Reiniciar Apache
service apache2 restart

# Configurar iptables para bloquear tráfego de IP específico (substitua pelo IP real)
iptables -A INPUT -s IP_MALICIOSO -j DROP

# Configurar iptables para mitigar ataques DDoS (limitar conexões)
iptables -A INPUT -p tcp --syn -m connlimit --connlimit-above 50 -j DROP

# Configurar iptables para limitar a taxa de novas conexões (substitua pela sua interface)
iptables -A INPUT -p tcp --dport 80 -i eth0 -m state --state NEW -m recent --set
iptables -A INPUT -p tcp --dport 80 -i eth0 -m state --state NEW -m recent --update --seconds 60 --hitcount 20 -j DROP

# Configurar iptables para evitar ataques ICMP e UDP flood
iptables -A INPUT -p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT
iptables -A INPUT -p icmp -j DROP
iptables -A INPUT -p udp --dport 53 -m limit --limit 1/s -j ACCEPT
iptables -A INPUT -p udp -j DROP

# Salvar regras iptables
service netfilter-persistent save
service netfilter-persistent reload

echo "Script concluído!"
