#!/bin/bash

############ EXTRA STUFF TO HELP HIGH TRAFFIC (DDOS) ##################

###################################################################################################################
# _|___|___|___|___|___|___|___|___|___|___|___|___|                                                             ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__        IPTables: Linux's Main line of Defense               ##
# _|___|___|___|___|___|___|___|___|___|___|___|___|        IPTables: Linux's way of saying no to DoS kids       ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__                                                             ##    
# _|___|___|___|___|___|___|___|___|___|___|___|___|        Version 1.0.0 -                                      ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__        IPTables Script created by p0w3r0ff                  ##
# _|___|___|___|___|___|___|___|___|___|___|___|___|                                                             ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__        Sources used and Studied;                            ##
# _|___|___|___|___|___|___|___|___|___|___|___|___|                                                             ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__     http://ipset.netfilter.org/iptables.man.html            ##
# _|___|___|___|___|___|___|___|___|___|___|___|___|                                                             ##
# ___|___|___|___|___|___|___|___|___|___|___|___|__                                                             ##
###################################################################################################################

# Crie conjuntos IPSET para Europa e Brasil
ipset create europe hash:net
ipset create brazil hash:net

# Adicione faixas de IPs associadas à Europa
wget -O - https://iptodns.com/api/ip/country/EU | xargs -I {} ipset add europe {}

# Adicione faixas de IPs associadas ao Brasil
wget -O - https://iptodns.com/api/ip/country/BR | xargs -I {} ipset add brazil {}

# Crie uma regra iptables para permitir tráfego de Europa e Brasil
iptables -A INPUT -m set --match-set europe src -j ACCEPT
iptables -A INPUT -m set --match-set brazil src -j ACCEPT

# Bloqueie todo o tráfego não especificado
iptables -A INPUT -j DROP

# Salve as configurações
service iptables save
service iptables restart
